### ISSUE TITLE
If CRAN requests more split before 'rxode2' admission, the code is currently brittle

### ISSUE THREAD

**Issue by mattfidler** [nlmixr2/rxode2parse#1]
Need a way to dynamically link the binary locations without hard coding them.

**Comment by billdenney** [comment]
Is the main purpose of this package to read in either rxode2-coded or nlmixr2-coded models and convert them to C++ code?  (Does it do more than that, like setup the UI object?  At a glance, I don't think so, but I'm not certain.)  Is this something that @joecodemonkey may be able to help with?

**Comment by mattfidler** [comment]
The purpose is:

- read rxode2 models (not ui) and generate code/variables from the code
- Push high compile computation from 'stan' into another package.

I am almost done with fixing this.  Basically I'm giving an arbitrary hook to allow `rxode2` models to generate the proper code  for C/C++ functions that people may wish to add (or modify in case I need to split it)
